<div class="row">
    @include('dashboard.dashboardWidgetItem', ['title' => 'Űrlap',
                                                'route' => 'questionnaires.index',
                                                'icon' => 'ion ion-stats-bars',
                                                'box' => 'small-box bg-success',
                                                'label' => 'Össz',
                                                'endlabel' => 'db',
                                                'function' => number_format(ToolsClass::modelCount('Questionnaires'),0,",",".") ])
    @include('dashboard.dashboardWidgetItem', ['title' => 'Voucher',
                                                'route' => 'vouchers.index',
                                                'icon' => 'ion-pie-graph',
                                                'box' => 'small-box bg-danger',
                                                'label' => 'Össz',
                                                'endlabel' => 'db',
                                                'function' => number_format(ToolsClass::modelCount('Vouchers'),0,",",".") ])
    @include('dashboard.dashboardWidgetItem', ['title' => 'Partner',
                                                'route' => 'partners.index',
                                                'icon' => 'ion ion-person-add',
                                                'box' => 'small-box bg-warning',
                                                'label' => 'Össz',
                                                'endlabel' => 'db',
                                                'function' => number_format(ToolsClass::modelCount('Partners'),0,",",".") ])
    @include('dashboard.dashboardWidgetItem', ['title' => 'Sorsolás',
                                                'route' => 'partners.index',
                                                'icon' => 'ion ion-bag',
                                                'box' => 'small-box bg-info',
                                                'label' => 'Össz',
                                                'endlabel' => 'db',
                                                'function' => number_format(0,0,",",".") ])
{{--                                                'function' => number_format(ToolsClass::modelCount('lotteries'),0,",",".") ])--}}
</div>

