<div class="row">
    @include('admin.adminWidgetItem', ['title' => 'Output files',
                                                'icon' => 'fas fa-trash-alt',
                                                'box' => 'small-box bg-danger',
                                                'label' => 'File össz',
                                                'endlabel' => 'db',
                                                'action' => "btn btn-default deleteOutputButton",
                                                'btnName' => 'Output törlés',
                                                'btnTitle' => 'Output törlés',
                                                'function' => number_format(App\Classes\txtFileCountClass::txtFileCount(),0,",",".") ])
    @include('admin.adminWidgetItem', ['title' => 'Adatbázis adatok',
                                                'icon' => 'fas fa-database',
                                                'box' => 'small-box bg-warning',
                                                'label' => 'Adatbázis tábla össz',
                                                'endlabel' => 'db',
                                                'action' => "btn btn-default truncateButton",
                                                'btnName' => 'Adatbázis törlés',
                                                'btnTitle' => 'Adatbázis törlés',
                                                'function' => number_format(App\Classes\txtFileCountClass::canBeDeletedTables(),0,",",".") ])
    @include('admin.adminWidgetItem', ['title' => 'Log file törlés',
                                                'icon' => 'fas fa-sign-in-alt',
                                                'box' => 'small-box bg-primary',
                                                'label' => 'Login rekord',
                                                'endlabel' => 'db',
                                                'action' => "btn btn-default loginButton",
                                                'btnName' => 'Login törlés',
                                                'btnTitle' => 'Login törlés',
                                                'function' => number_format(App\Models\Logitems::where('logitemtype_id', 1)->get()->count(),0,",",".") ])
    @include('admin.adminWidgetItem', ['title' => 'Összes log rekord törlés',
                                                'icon' => 'fa fa-box',
                                                'box' => 'small-box bg-warning',
                                                'label' => 'Log rekordok össz',
                                                'endlabel' => 'db',
                                                'action' => "btn btn-default logAllButton",
                                                'btnName' => 'Log rekordok törlés',
                                                'btnTitle' => 'Log rekordok törlés',
                                                'function' => number_format(App\Models\Logitems::get()->count(),0,",",".") ])
</div>

